micronaut:
  application:
    name: keyManager

datasources:
  default:
    url: ${DB_URL:`jdbc:postgresql://localhost:5440/keymanagergrpc`}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    javax:
      persistence:
        validation:
          mode: none


itau:
  contas:
    url: ${ITAU_URL:`http://localhost:9091/api/v1`}


bacen:
  pix:
    url: ${BACEN_URL:`http://localhost:8082/api/v1`}



#datasources:
#  default:
#    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
#    driverClassName: org.h2.Driver
#    username: sa
#    password: ''
#    schema-generate: CREATE_DROP
#    dialect: H2
#    jpa.default.properties.hibernate.hbm2ddl.auto: update
